function filtered_metrics = filter_metrics(metrics,rows,cols,nroutes,algo)
    hits = cellfun(@(x) x.test_output.test_parameters.rows == rows && ...
        x.test_output.test_parameters.cols == cols && ...
        x.test_output.test_parameters.nroutes == nroutes && ...
        strcmp(x.test_output.algorithm, algo), metrics);
    filtered_metrics = metrics(hits);
end